# version: '3.8'

# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: asilbekmuminov
#       POSTGRES_PASSWORD: azizbekloh
#       POSTGRES_DB: construction_db
#       DATABASE_URL_LOCAL: postgres://asilbekmuminov:azizbekloh@localhost:5432/construction_db
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_HOST: ${DATABASE_HOST:-localhost}
#       DATABASE_PORT: ${DATABASE_PORT:-5432}
#       DATABASE_USERNAME: ${DATABASE_USERNAME:-asilbekmuminov}
#       DATABASE_PASSWORD: ${DATABASE_PASSWORD:-azizbekloh}
#       DATABASE_NAME: ${DATABASE_NAME:-construction_db}
#       DATABASE_URL_LOCAL: ${DATABASE_URL_LOCAL:-postgres://asilbekmuminov:azizbekloh@localhost:5432/construction_db}
#     command: npm run start:prod

# volumes:
#   pgdata:
