version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: asilbekmuminov
      POSTGRES_PASSWORD: azizbekloh
      POSTGRES_DB: construction_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: asilbekmuminov
      DATABASE_PASSWORD: azizbekloh
      DATABASE_NAME: construction_db
    command: npm run start:prod

volumes:
  pgdata:
